---
title: Book Talk
author: Taylor Contreras
date: '2021-05-05'
slug: book-talk
categories: []
tags: []
description: ''
---
Like nearly everyone on the planet, I had a New Year's resolution. I wanted to read more books. I have loved reading for as long as I can remember. Yet, I think the last time I had really read more than the books assigned for school was my sophomore year of high school. I got busy applying for college and getting jobs. It didn't bother me until I was trapped at home every day. The COVID-19 pandemic made me realize all that I had lost interest in. 

I wanted to get back into it, but I didn't know where to start. I had been in a "reading slump" for nearly four years. None of my friends read and I didn't think I would be interested in any of the recommendations my family suggested. I came across a tik-tok one day discussing how to fix this. The girl in the video said: How could you possibly read older books when the last thing you read was fantasy when you were a teen? You need to start where you left off. 

I hadn't thought of it like that. I thought everyone just jumped back into reading what was age appropriate. I gave it a try. It was embarrassing to admit that I was re-reading the Percy Jackson series as a 20 year old college student. But I remembered how fun it was to read and the next thing I knew, I was reading the two follow-up series. That became adult fantasy/greek mythology. Then that transitioned into giving classic novels, murder mysteries and thrillers a try. Now? My love for reading is unmatched! The only dilemma? I constantly need money to fuel my reignited book addiction. 

Moral of the story: Read what you loved last. Fall in love all over again. 